language: objective-c
osx_image: xcode9.4
install:
  - bundle install
before_script:
  - bundle exec danger
script:
  - swift package generate-xcodeproj
  - bundle exec fastlane test
after_success:
  - bash <(curl -s https://codecov.io/bash)
